# Template for release drafts
name-template: 'v$NEXT_MINOR_VERSION'   # You can switch to $NEXT_MINOR_VERSION or $NEXT_MAJOR_VERSION
tag-template: 'v$NEXT_MINOR_VERSION'

# Exclude PRs with this label from release notes
exclude-labels:
  - automated

categories:
  - title: "🚀 Features"
    labels:
      - feature
  - title: "🐛 Bug Fixes"
    labels:
      - fix
      - bug
  - title: "🧰 Maintenance"
    labels:
      - chore
      - refactor
  - title: "Dependencies"
    labels:
      - dependencies
      - javascript

change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
change-title-template: '### $TITLE'
template: |
  ## Changes

  $CHANGES
